"""empty message

Revision ID: 4468c32f9a67
Revises: 1b7bef226251
Create Date: 2023-06-29 14:56:58.724177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4468c32f9a67'
down_revision = '1b7bef226251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_favorites_comment_id_comments', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_favorites_listing_id_listings'), 'listings', ['listing_id'], ['id'])
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_favorites_listing_id_listings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_favorites_comment_id_comments', 'comments', ['comment_id'], ['id'])
        batch_op.drop_column('listing_id')

    # ### end Alembic commands ###
